### ISSUE TITLE
Speed-Calculation

### ISSUE THREAD

**Issue by DonCaramello** [SubstituteCS/Pokesposed#3]
smth wrong with the speed while "walk to point" is activated:
its way to fast, didnt count for eggs to hatch. i recorded:
1km took me ~140sek to "run" 
--> approx speed ~25km/h not 8 km/h

---

tested with:
- Nexus 5 with CyanogenMod 13.0 (Android 6.0.1)
- xposed 3.0 alpha4
- pokemonGo (playstore version) 0.29.2

**Comment by DonCaramello** [comment]
_edit_
just read your comment at reddit with your wanted speed of "7.2 km / hour" 
my measured speed would be exactly 7.2 m/sek
maybe this helps you finding your tippo :)

**Comment by SubstituteR** [comment]
Hi, this does help me.  If your speed is 7.2 m / second, that would be 25.92 kmh.  This means I did a goof while converting my numbers :frowning: 
I'll fix it :grin:

**Comment by SubstituteR** [comment]
Should be fixed.
