### ISSUE TITLE
cannot access  method void android.location.GpsStatus.setStatus

### ISSUE THREAD

**Issue by lordfiSh** [SubstituteCS/Pokesposed#4]
One Plus Two, OxygenOS Version 3.0.2 (Offical Fimware) = Android 6.0.1

Always starting in the middle of the Ocean. Set Location before starting the Game.
After Device Restart, without the App open also located there. Restarting again and clearing the application cache fix the Location to normal my real location.

But the module still dont work, I can set my Location, clicking a few times enable/disable and move to locations, but in pokemon im still at the ocean: 

> 07-23 09:03:01.586 E/Xposed  ( 5461):     at android.location.LocationManager.getGpsStatus(<Xposed>)
> 07-23 09:03:01.586 E/Xposed  ( 5461):     at adpu.onGpsStatusChanged(:com.google.android.gms:716)
> 07-23 09:03:01.586 E/Xposed  ( 5461):     at android.location.LocationManager$GpsStatusListenerTransport$1.handleMessage(LocationManager.java:1534)
> 07-23 09:03:01.586 E/Xposed  ( 5461):     at android.os.Handler.dispatchMessage(Handler.java:102)
> 07-23 09:03:01.586 E/Xposed  ( 5461):     at android.os.Looper.loop(Looper.java:152)
> 07-23 09:03:01.586 E/Xposed  ( 5461):     at android.os.HandlerThread.run(HandlerThread.java:61)
> 07-23 09:03:01.589 I/Xposed  ( 1230): PokemonDontGo:mod: Hooked _handle....
> 07-23 09:03:01.592 I/Xposed  ( 1230): PokemonDontGo:mod: Hooked _handle....
> 07-23 09:03:01.598 I/Xposed  ( 1230): PokemonDontGo:mod: Hooked _handle....
> 07-23 09:03:01.603 I/Xposed  (18386): : Read Data! :
> 07-23 09:03:01.603 I/Xposed  (18386): : Executed :
> 07-23 09:03:01.612 I/Xposed  (18386): : Read Data! :
> 07-23 09:03:01.612 I/Xposed  (18386): : Executed :
> 07-23 09:03:03.577 I/Xposed  ( 1230): PokemonDontGo:mod: Hooked _handle....
> 07-23 09:03:03.578 I/Xposed  ( 1230): PokemonDontGo:mod: Hooked _handle....
> 07-23 09:03:03.578 E/Xposed  (18386): java.lang.IllegalAccessException: Class java.lang.Class<com.vivek.xposedpokemon.XGpsStatus> cannot access  method void android.location.GpsStatus.setStatus(int, int[], float[], float[], float[], int, int, int) of class java.lang.Class<android.location.GpsStatus>
> 07-23 09:03:03.578 E/Xposed  (18386):     at java.lang.reflect.Method.invoke(Native Method)
> 07-23 09:03:03.578 E/Xposed  (18386):     at com.vivek.xposedpokemon.XGpsStatus.afterHookedMethod(XGpsStatus.java:58)
> 07-23 09:03:03.578 E/Xposed  (18386):     at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:348)
> 07-23 09:03:03.578 E/Xposed  (18386):     at android.location.LocationManager.getGpsStatus(<Xposed>)
> 07-23 09:03:03.578 E/Xposed  (18386):     at com.nianticlabs.nia.location.LocationManagerProvider$2.onGpsStatusChanged(LocationManagerProvider.java:155)
> 07-23 09:03:03.578 E/Xposed  (18386):     at android.location.LocationManager$GpsStatusListenerTransport$1.handleMessage(LocationManager.java:1534)
> 07-23 09:03:03.578 E/Xposed  (18386):     at android.os.Handler.dispatchMessage(Handler.java:102)
> 07-23 09:03:03.578 E/Xposed  (18386):     at android.os.Looper.loop(Looper.java:152)
> 07-23 09:03:03.578 E/Xposed  (18386):     at android.os.HandlerThread.run(HandlerThread.java:61)
> 07-23 09:03:03.586 E/Xposed  ( 5461): java.lang.IllegalAccessException: Class java.lang.Class<com.vivek.xposedpokemon.XGpsStatus> cannot access  method void android.location.GpsStatus.setStatus(int, int[], float[], float[], float[], int, int, int) of class java.lang.Class<android.location.GpsStatus>
> 07-23 09:03:03.586 E/Xposed  ( 5461):     at java.lang.reflect.Method.invoke(Native Method)
> 07-23 09:03:03.586 E/Xposed  ( 5461):     at com.vivek.xposedpokemon.XGpsStatus.afterHookedMethod(XGpsStatus.java:58)
> 07-23 09:03:03.586 E/Xposed  ( 5461):     at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:348)
> 07-23 09:03:03.586 E/Xposed  ( 5461):     at android.location.LocationManager.getGpsStatus(<Xposed>)
> 07-23 09:03:03.586 E/Xposed  ( 5461):     at adpu.onGpsStatusChanged(:com.google.android.gms:716)
> 07-23 09:03:03.586 E/Xposed  ( 5461):     at android.location.LocationManager$GpsStatusListenerTransport$1.handleMessage(LocationManager.java:1534)
> 07-23 09:03:03.586 E/Xposed  ( 5461):     at android.os.Handler.dispatchMessage(Handler.java:102)
> 07-23 09:03:03.586 E/Xposed  ( 5461):     at android.os.Looper.loop(Looper.java:152)
> 07-23 09:03:03.586 E/Xposed  ( 5461):     at android.os.HandlerThread.run(HandlerThread.java:61)
> 07-23 09:03:03.590 I/Xposed  (18386): : Read Data! :
> 07-23 09:03:03.591 I/Xposed  (18386): : Executed :
> 07-23 09:03:03.601 I/Xposed  ( 1230): PokemonDontGo:mod: Hooked _handle....
> 07-23 09:03:04.591 I/Xposed  (18386): : Read Data! :
> 07-23 09:03:04.592 I/Xposed  (18386): : Executed :
> 07-23 09:03:05.568 I/Xposed  ( 1230): PokemonDontGo:mod: Hooked _handle....
> 07-23 09:03:05.569 I/Xposed  ( 1230): PokemonDontGo:mod: Hooked _handle....
> 07-23 09:03:05.575 E/Xposed  (18386): java.lang.IllegalAccessException: Class java.lang.Class<com.vivek.xposedpokemon.XGpsStatus> cannot access  method void android.location.GpsStatus.setStatus(int, int[], float[], float[], float[], int, int, int) of class java.lang.Class<android.location.GpsStatus>
> 07-23 09:03:05.575 E/Xposed  (18386):     at java.lang.reflect.Method.invoke(Native Method)
> 07-23 09:03:05.575 E/Xposed  (18386):     at com.vivek.xposedpokemon.XGpsStatus.afterHookedMethod(XGpsStatus.java:58)
> 07-23 09:03:05.575 E/Xposed  (18386):     at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:348)
> 07-23 09:03:05.575 E/Xposed  (18386):     at android.location.LocationManager.getGpsStatus(<Xposed>)
> 07-23 09:03:05.575 E/Xposed  (18386):     at com.nianticlabs.nia.location.LocationManagerProvider$2.onGpsStatusChanged(LocationManagerProvider.java:155)
> 07-23 09:03:05.575 E/Xposed  (18386):     at android.location.LocationManager$GpsStatusListenerTransport$1.handleMessage(LocationManager.java:1534)
> 07-23 09:03:05.575 E/Xposed  (18386):     at android.os.Handler.dispatchMessage(Handler.java:102)
> 07-23 09:03:05.575 E/Xposed  (18386):     at android.os.Looper.loop(Looper.java:152)
> 07-23 09:03:05.575 E/Xposed  (18386):     at android.os.HandlerThread.run(HandlerThread.java:61)
> 07-23 09:03:05.583 I/Xposed  ( 1230): PokemonDontGo:mod: Hooked _handle....
> 07-23 09:03:05.597 E/Xposed  ( 5461): java.lang.IllegalAccessException: Class java.lang.Class<com.vivek.xposedpokemon.XGpsStatus> cannot access  method void android.location.GpsStatus.setStatus(int, int[], float[], float[], float[], int, int, int) of class java.lang.Class<android.location.GpsStatus>
> 07-23 09:03:05.597 E/Xposed  ( 5461):     at java.lang.reflect.Method.invoke(Native Method)
> 07-23 09:03:05.597 E/Xposed  ( 5461):     at com.vivek.xposedpokemon.XGpsStatus.afterHookedMethod(XGpsStatus.java:58)
> 07-23 09:03:05.597 E/Xposed  ( 5461):     at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:348)
> 07-23 09:03:05.597 E/Xposed  ( 5461):     at android.location.LocationManager.getGpsStatus(<Xposed>)
> 07-23 09:03:05.597 E/Xposed  ( 5461):     at adpu.onGpsStatusChanged(:com.google.android.gms:716)
> 07-23 09:03:05.597 E/Xposed  ( 5461):     at android.location.LocationManager$GpsStatusListenerTransport$1.handleMessage(LocationManager.java:1534)
> 07-23 09:03:05.597 E/Xposed  ( 5461):     at android.os.Handler.dispatchMessage(Handler.java:102)
> 07-23 09:03:05.597 E/Xposed  ( 5461):     at android.os.Looper.loop(Looper.java:152)
> 07-23 09:03:05.597 E/Xposed  ( 5461):     at android.os.HandlerThread.run(HandlerThread.java:61)
> 07-23 09:03:05.599 I/Xposed  (18386): : Read Data! :
> 07-23 09:03:05.600 I/Xposed  (18386): : Executed :
> 07-23 09:03:06.599 I/Xposed  (18386): : Read Data! :
> 07-23 09:03:06.600 I/Xposed  (18386): : Executed :
> 07-23 09:03:07.585 I/Xposed  ( 1230): PokemonDontGo:mod: Hooked _handle....
> 07-23 09:03:07.588 I/Xposed  ( 1230): PokemonDontGo:mod: Hooked _handle....
> 07-23 09:03:07.593 E/Xposed  (18386): java.lang.IllegalAccessException: Class java.lang.Class<com.vivek.xposedpokemon.XGpsStatus> cannot access  method void android.location.GpsStatus.setStatus(int, int[], float[], float[], float[], int, int, int) of class java.lang.Class<android.location.GpsStatus>
> 07-23 09:03:07.593 E/Xposed  (18386):     at java.lang.reflect.Method.invoke(Native Method)
> 07-23 09:03:07.593 E/Xposed  (18386):     at com.vivek.xposedpokemon.XGpsStatus.afterHookedMethod(XGpsStatus.java:58)
> 07-23 09:03:07.593 E/Xposed  (18386):     at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:348)
> 07-23 09:03:07.593 E/Xposed  (18386):     at android.location.LocationManager.getGpsStatus(<Xposed>)
> 07-23 09:03:07.593 E/Xposed  (18386):     at com.nianticlabs.nia.location.LocationManagerProvider$2.onGpsStatusChanged(LocationManagerProvider.java:155)
> 07-23 09:03:07.593 E/Xposed  (18386):     at android.location.LocationManager$GpsStatusListenerTransport$1.handleMessage(LocationManager.java:1534)
> 07-23 09:03:07.593 E/Xposed  (18386):     at android.os.Handler.dispatchMessage(Handler.java:102)
> 07-23 09:03:07.593 E/Xposed  (18386):     at android.os.Looper.loop(Looper.java:152)
> 07-23 09:03:07.593 E/Xposed  (18386):     at android.os.HandlerThread.run(HandlerThread.java:61)
> 07-23 09:03:07.601 I/Xposed  (18386): : Read Data! :
> 07-23 09:03:07.601 I/Xposed  (18386): : Executed :
> 07-23 09:03:07.615 I/Xposed  ( 1230): PokemonDontGo:mod: Hooked _handle....
> 07-23 09:03:07.615 E/Xposed  ( 5461): java.lang.IllegalAccessException: Class java.lang.Class<com.vivek.xposedpokemon.XGpsStatus> cannot access  method void android.location.GpsStatus.setStatus(int, int[], float[], float[], float[], int, int, int) of class java.lang.Class<android.location.GpsStatus>
> 07-23 09:03:07.615 E/Xposed  ( 5461):     at java.lang.reflect.Method.invoke(Native Method)
> 07-23 09:03:07.615 E/Xposed  ( 5461):     at com.vivek.xposedpokemon.XGpsStatus.afterHookedMethod(XGpsStatus.java:58)
> 07-23 09:03:07.615 E/Xposed  ( 5461):     at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:348)
> 07-23 09:03:07.615 E/Xposed  ( 5461):     at android.location.LocationManager.getGpsStatus(<Xposed>)
> 07-23 09:03:07.615 E/Xposed  ( 5461):     at adpu.onGpsStatusChanged(:com.google.android.gms:716)
> 07-23 09:03:07.615 E/Xposed  ( 5461):     at android.location.LocationManager$GpsStatusListenerTransport$1.handleMessage(LocationManager.java:1534)
> 07-23 09:03:07.615 E/Xposed  ( 5461):     at android.os.Handler.dispatchMessage(Handler.java:102)
> 07-23 09:03:07.615 E/Xposed  ( 5461):     at android.os.Looper.loop(Looper.java:152)
> 07-23 09:03:07.615 E/Xposed  ( 5461):     at android.os.HandlerThread.run(HandlerThread.java:61)
> 07-23 09:03:09.573 I/Xposed  ( 1230): PokemonDontGo:mod: Hooked _handle....
> 07-23 09:03:09.575 I/Xposed  (18386): : Read Data! :
> 07-23 09:03:09.575 I/Xposed  (18386): : Executed :

**Comment by SubstituteR** [comment]
Thank you for this log, I will into the issue.  If you PM me your Skype on Reddit I can work with you to make a build that will 100% work.

**Comment by SubstituteR** [comment]
07-23 09:03:03.578 I/Xposed ( 1230): PokemonDontGo:mod: Hooked _handle....
07-23 09:03:03.578 E/Xposed (18386): java.lang.IllegalAccessException: Class java.lang.Class cannot access method void android.location.GpsStatus.setStatus(int, int[], float[], float[], float[], int, int, int) of class java.lang.Class
07-23 09:03:03.578 E/Xposed (18386): at java.lang.reflect.Method.invoke(Native Method)
07-23 09:03:03.578 E/Xposed (18386): at com.vivek.xposedpokemon.XGpsStatus.afterHookedMethod(XGpsStatus.java:58)
07-23 09:03:03.578 E/Xposed (18386): at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:348)
07-23 09:03:03.578 E/Xposed (18386): at android.location.LocationManager.getGpsStatus()
07-23 09:03:03.578 E/Xposed (18386): at com.nianticlabs.nia.location.LocationManagerProvider$2.onGpsStatusChanged(LocationManagerProvider.java:155)
07-23 09:03:03.578 E/Xposed (18386): at android.location.LocationManager$GpsStatusListenerTransport$1.handleMessage(LocationManager.java:1534)

You have a module conflict.  It looks like com.vivek.xposedpokemon.XGpsStatus.afterHookedMethod is causing the issue, disable XGpsStatus and try again

**Comment by lordfiSh** [comment]
I had several modules installed, but problery did't restarted the device. Thanks for the hint, after restart its working fine
