### ISSUE TITLE
Pokesposed has stopped when force closing Pokemon Go

### ISSUE THREAD

**Issue by cfharp** [SubstituteCS/Pokesposed#7]
Android 6.0.1 XenonHD (6/19/16)

Whenever I force close Pokemon (in instances where it freezes or similar), I get a message that Pokesposed has stopped. Not a big deal, but if it's something easy to fix that would be great.

Thanks SubstituteCS!

**Comment by SubstituteR** [comment]
It might be due to Pokemon not unbinding from the service cleanly, and the service not handling that properly.  Thank you for bringing this up.  I have been focusing on cleaning up and removing bugs for the past few days (the time that I have actually spent developing)

**Comment by SubstituteR** [comment]
Should be fixed.
